### ISSUE TITLE
Portal doesn't update in this case:

### ISSUE THREAD

**Issue by MarcGodard** [donejs/portal-ssr#6]
If in your app.js steal imports you use the same variable name (not PageOne and PageTwo, but just Page for example), the portals do not update. Some documentation should be provided or a warning if the same name is used.

```
      case 'home': {
        return window.steal.import('~/pages/page-one.component').then(({default: Page}) => {
          return new Page()
        })
      }

      case 'page-two': {
        return window.steal.import('~/pages/page-two.component').then(({default: Page}) => {
          return new Page()
        })
      }
```

**Comment by chasenlehara** [comment]
This sounds like a bug, but I’m surprised that this could even be a bug because the variable name you use to return a new component instance shouldn’t have anything to do with how the portal is rendered.

@matthewp what do you think?

**Comment by matthewp** [comment]
I think there's likely a bug here but the variable name being the source seems pretty unlikely. Would need an example to proceed.

**Comment by MarcGodard** [comment]
I wasn't able to reproduce in this example. So something else is causing it. My other project is an open project. I will check tomorrow if the issue is still there. Maybe it was some other artifact, but changing the variable names IS what fixed it. It was the only thing I changed. I will link the other repo here once I confirm the issue is still there. But this is very minor.

**Comment by MarcGodard** [comment]
I can no longer reproduce this. Closing for now, but will keep it in mind.
